name: album_viewer
description: A Flutter album viewer application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # For making HTTP requests to the API
  http: ^1.1.0

  # For state management (BLoC pattern)
  flutter_bloc: ^8.1.3

  # For navigation between screens
  go_router: ^10.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true